print ("Welcome to the world of programming")
print ("My name is Joshitha.")
print ("How old are you?")
print (14)
print ("What year is this?")
print (2026)
print ("What is your name? \n How old are you?")
print ("If you live in Texas, \nthen you live in the USA.")
print ("How old are you?")
print ("I am", 14)
print ("This year is", 2026)